site_name:         'Canterbury Punting Company'
logo_w:            '210'
logo_h:            '68'

facebook:          'https://www.facebook.com/CambridgePuntingCompany'
twitter:           'https://twitter.com/CambridgePuntCo'
instagram:         'https://instagram.com/cambridgepuntingcompany/'

contact_email:     'ashley@canterburypunting.co.uk'
contact_tel_human: '07786 332666'
contact_tel_full:  '+447786332666'

booking_email:     'ashley@canterburypunting.co.uk'
