site_name:         'Canterbury Punting Company'
logo_w:            '210'
logo_h:            '68'

facebook:          'https://www.facebook.com/CanterburyPuntingCompany'
twitter:           'https://twitter.com/CanterburyPunt'
instagram:         'https://instagram.com/canterburypuntingcompany/'

mail_domain:       'canterburypunting.co.uk'
contact_email:     'ashley@canterburypunting.co.uk'
contact_tel_human: '01227 464797'
contact_tel_full:  '+441227464797'

booking_email:     'ashley@canterburypunting.co.uk'
