site_name:         'Cambridge Punting Company'
logo_w:            '210'
logo_h:            '72'

facebook:          'https://www.facebook.com/CambridgePuntingCompany'
twitter:           'https://twitter.com/CambridgePuntCo'
instagram:         'https://instagram.com/cambridgepuntingcompany/'

mail_domain:       'cambridgepuntingcompany.co.uk'
contact_email:     'bookings@cambridgepuntingcompany.co.uk'
contact_tel_human: '07786 332666'
contact_tel_full:  '+447786332666'

booking_email:     'bookings@cambridgepuntingcompany.co.uk'
