time_zone:         'Pacific/Auckland'
country_dial_code: '64'

site_name:         'Wine Sentience'
logo_w:            '160'
logo_h:            '160'
footer_summary:    "<strong>Wine Sentience</strong> - The Exchange, 17A Allen Street, Te Aro, Wellington 6011, New Zealand"

facebook:          ''
twitter:           '' # 'https://x.com/WineSentience/'
instagram:         'https://www.instagram.com/winesentience/'

mail_domain:       'winesentience.com'
contact_email:     'stephen@winesentience.com'
contact_tel_human: '' # '021 488 855'
contact_tel_full:  '' # '+6421488855'

booking_email:     'stephen@winesentience.com'
