site_name:         'Canterbury Punting Company'
logo_w:            '210'
logo_h:            '68'

facebook:          'https://www.facebook.com/CanterburyPuntingCompany'
twitter:           'https://twitter.com/CanterburyPunt'
instagram:         'https://instagram.com/canterburypuntingcompany/'
google:            'https://plus.google.com/110659658154563209853/posts'

contact_email:     'ashley@canterburypunting.co.uk'
contact_tel_human: '07786 332666'
contact_tel_full:  '+447786332666'

booking_email:     'ashley@canterburypunting.co.uk'
