# PostgreSQL. Versions 8.2 and up are supported.
#
development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: hcms_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: hcms_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: hcms_production
  username: hcms
  password: <%= ENV['HCMS_DATABASE_PASSWORD'] %>
