default: &default
  time_zone:         'Pacific/Auckland'
  country_code:      'NZ' # ISO 3166 alpha-2

  site_name:         'Wine Sentience'
  logo_w:            '160'
  logo_h:            '160'

  mail_domain:       'winesentience.com'
  booking_email:     'stephen@winesentience.com' # The "to" address for ad hoc booking enquiries sent to you
  orders_email:      'stephen@winesentience.com' # The "from" address in event sales messages sent to customers
  contact_email:     'stephen@winesentience.com'
  contact_tel_human: '021 488 855'
  contact_tel_full:  '+6421488855'

  currency:          'NZD' # 3-letter ISO symbol; only relevant if you sell event tickets
  hide_booking_date: true  # Just a default; you can change it when editing booking pages
  hide_order_notes:  true  # Not just a default; permanently hide the "other notes" field for orders
  no_refunds_window: 3     # In days, before event starts; zero for "refunds always offered"

  footer_summary:    "<strong>Wine Sentience</strong> - The Exchange, 17A Allen Street, Te Aro, Wellington 6011, New Zealand"
  hide_contact_info: true
  facebook:          ''
  twitter:           '' # 'https://x.com/WineSentience/'
  instagram:         'https://www.instagram.com/winesentience/'

  # If supporting paid orders via Stripe, this configuration section applies.
  #
  stripe:
    checkout_background: '#f5f5ef'

  # Custom redirections go here, for cases where a site has been migrated; blog
  # articles first (requested path base -> blog page's slug) - this tries to then
  # match the *last* part of the requested path against an article's slug -
  # followed by other custom maps (requested path base -> general page's slug).
  # Failing any matches here, the last part of the path ".../foo/bar" -> "bar")
  # is used to try and find a page by slug, else, 404.
  #
  blog_mappings:
    'blog':               'blog'
    'tastings-events':    'previous-events'
    'tastings-education': 'previous-classes'
    'whats-on':           'previous-classes'

  page_mappings:
    'our-team':           'home'
    'about':              'home'
    'contact':            'contact-us'
    'the-hub':            'contact-us'
    'maison-vauron':      'contact-us'
    'trade-portal':       'contact-us'
    'tastings-private':   'private-tastings'
    'tasting-enquiry':    'private-tastings'
    'cellar-door':        'private-tastings'
    'giftcards':          'private-tastings'
    'education':          'private-tastings'
    'services':           'private-tastings'
    'shop':               'private-tastings'
    'nouvelle-2021':      'previous-events'
    'umberground-2024':   'previous-events'

  # Do not generate statistics for paths starting with these prefixes that have
  # not matched other endpoints and fallen through to the redirection system.
  #
  statistics_ignore:
    match_exactly:
      - 'admin'
      - 'assets'
      - 'cgi-bin'
      - 'components'
      - 'files'
      - 'images'
      - 'local'
      - 'login'
      - 'php'
      - 'plugins'
      - 'modules'
      - 'template'
      - 'system'
      - 'wordpress'
      - 'wp'
    starts_with:
      - '.'
      - 'wp-'
      - 'admin/'
      - 'assets/'
      - 'login/'
      - 'upload'
      - 'vendor'
    found_anywhere:
      - 'phpinfo'
      - '.env'
      - '.php'
      - '/wp-'

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
